apiVersion: apps/v1
kind: Deployment
metadata:
  name: shiro-action-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiro-action
  template:
    metadata:
      labels:
        app: shiro-action
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: shiro-action-container
          image: openjdk:8-alpine
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: data
              mountPath: /home
              name: font
              mountPath: /usr/share/fonts
          command: ["/bin/sh","-ce","java -jar /home/shiro-action.jar"]
      volumes:
        - name: data
          hostPath:
            path: /home/shiro-action/
          name: font
          mount: /usr/share/fonts

---

apiVersion: v1
kind: Service
metadata:
  name: shiro-action-service
  labels:
    app: shiro-action
spec:
  type: NodePort
  externalIPs:
    - 10.0.4.3
  ports:
    - port:  8081
      targetPort: 8081
      nodePort: 30010
  selector:
    app: shiro-action
